### PR TITLE
validation(req): New submission for Icali

### PR DESCRIPTION
**Pull request by nicolasdecorbez**
# checklist

- [x] I have created my repository
- [x] I have added a link to my submission in the corresponding field
- [x] I have documented my code ( :wink: )

Link: <https://github.com/nicolasdecorbez/icali>

### CODE REVIEW

**Comment by tbobm** [comment]
Hi @nicolasdecorbez !

Thank you for your submission. I'll try to take a look in the coming 24 hours and will report back with the review results.
I already peaked at your project, great work :rocket:

**Comment by tbobm** [comment]
# review

I reviewer your repository ! A couple of points to get back to before I can :heavy_check_mark: this submission:
- Your code requires a bit of linting
- Some parts of the code are a bit difficult to read / understand
- The featureset is :heavy_check_mark: !
- The packaging is nearly :heavy_check_mark: , it seems like you moved your sources but did not edit the `pyproject.yaml`

Great work ! I'll assign you back to the PR, ping me and ask for a review once your tackled these points. :wink: 

## Code quality

:warning:

I invite you to make your code [PEP8][pep8]-compliant ([PEP8 for humans][pep8-humans]) using `pycodestyle`.

Below are the outputs of `pycodestyle` (required) and `pylint` (a smarter linter that is also a great complement).
For example, `pylint` found some possibly undefined variables (`index` in `icali/csv_reader.py`)

- [ ] Use absolute imports when possible: `from icali import read_input`
- [ ] Using a `csv.DictReader` would allow you to avoid manipulating indexes and using dictionnaries instead
- [ ] try to use meaningful variable names
  - `e = Event()` could be replaced by `event = Event()`
  - you could also rename the `Event` class to something like `CalendarEvent`

_see the files below for a complete output_

## Documentation

Your README is great, simple and efficient. :heavy_check_mark: 

However, the [PEP257][pep257] describes how to document code using `docstrings`, this can be a nice starting point to documenting in a Pythonic way.
For example, avoir using `# --- #` in your code as it is not necessary. You may add docstrings to your functions and modules to describe what their goal is / how a function does stuff.

## As a list

- [ ] Installing using `poetry install` fails, see [icali-install.txt](https://github.com/open-subjects/open-subjects/files/6241304/icali-install.txt)
- [ ] I am not sure what the `Positions` class is mean to be (_and it might be more convenient to call it `Position`_)


## Files

[pycodestyle.txt](https://github.com/open-subjects/open-subjects/files/6239684/pycodestyle.txt)
[pylint.txt](https://github.com/open-subjects/open-subjects/files/6239685/pylint.txt)

[pep8-humans]: https://pep8.org/
[pep8]: https://www.python.org/dev/peps/pep-0008/
[pep257]: https://www.python.org/dev/peps/pep-0257/

**Review by tbobm — CHANGES_REQUESTED** [review]
See https://github.com/open-subjects/open-subjects/pull/24#issuecomment-811676460

**Comment by nicolasdecorbez** [comment]
hi @tbobm !

Thank you for your review, it gave me more knowledge and informations about Python's norms and lints. I'll try to fix my code before this week-end, I'll keep you in touch !

**Comment by nicolasdecorbez** [comment]
# New submission

Thanks to your feedback, I fixed my project. You can find it here : <https://github.com/nicolasdecorbez/icali>

## changes

Here is a list of all changes I made : 

- [x] Fixed `pyproject.toml`. You will now be able to run `icali` with `poetry`
- [x] Modified all sources using `pylint` and `pycodestyle` outputs to make it PEP8-compilant and PEP257-adapted 
- [x] Used `csv.DictReader` instead of `csv.reader` and meaningful variables names
- [x] Removed `Positions` class and `get_positions()` function (useless since `DictReader` implementation)
- [x] Added docstrings in each files.

**Pull request merged**
